### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte

### ISSUE THREAD

**Issue by LupaDE** [adafruit/Adafruit-WebIDE#277]
Hi all,
following code at line 3 produces an exception in Adafruits-WebIDE if in debugging mode, if it is executed in run mode no error occur:
1. import serial
2. port = serial.Serial("/dev/ttyAMA0", baudrate=115200, timeout=3.0)
3. rcv = port.read(99)

Exception Output:

Traceback (most recent call last):
  File "debugger.py", line 314, in start_debug
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/usr/share/adafruit/webide/repositories/my-pi-projects/MyWebRadio/serialtest.py", line 3, in <module>
    rcv = port.read(99)
  File "/usr/lib/python2.7/bdb.py", line 53, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/usr/lib/python2.7/bdb.py", line 88, in dispatch_return
    self.user_return(frame, arg)
  File "debugger.py", line 195, in user_return
    self._connection.send_json(ret)
  File "debugger.py", line 26, in send_json
    res = json.dumps(data, indent=None)
  File "/usr/lib/python2.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 263, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf8 in position 0: invalid start byte
--- Program Exited with an Exception ---

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
