### ISSUE TITLE
Debugging not working

### ISSUE THREAD

**Issue by somethingsomething88** [adafruit/Adafruit-WebIDE#329]
Hello,

after installation, I can access the WebIDE but when I attempt to debug, the status stays at initializing and I never see the red line popping up. Visualizer loads forever.

During installation, I also saw a few warnings:

**** Installing webide dependencies ****
npm WARN mongodb-core@1.2.32 requires a peer of kerberos@~0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

up to date in 22.564s
**** Adding default .bashrc file for webide user ****
Attempting to force reload date and time from ntp server
Reloading ntp configuration (via systemctl): ntp.service.
**** Starting the server...(please wait) ****
**** The Adafruit WebIDE is installed and running! ****
**** Commands: sudo systemctl {start,stop,restart} adafruit-webide ****
**** Navigate to http://raspberrypi.local:8080 to use the WebIDE

Thanks.

**Comment by alager** [comment]
Any resolution to this?  I'm having the same issue.  I didn't have the install errors, but run/debug do not work.

**Comment by negusm** [comment]
I saw the above warnings too...but I don't think they are the culprit.

Found the following in the syslog:

Mar 17 13:58:24 raspberrypi-waveshare webide[884]: start_debug
Mar 17 13:58:24 raspberrypi-waveshare webide[884]: true
Mar 17 13:58:24 raspberrypi-waveshare webide[884]: spawn debugger
Mar 17 13:58:24 raspberrypi-waveshare webide[884]: error: Shutting down from uncaughtException
Mar 17 13:58:24 raspberrypi-waveshare webide[884]: error: TypeError: Cannot read property 'python_version' of null
Mar 17 13:58:24 raspberrypi-waveshare webide[884]:     at /usr/share/adafruit/webide/helpers/python/debug_helper.js:35:55
Mar 17 13:58:24 raspberrypi-waveshare webide[884]:     at newArguments.(anonymous function) (/usr/share/adafruit/webide/node_modules/nedb/lib/executor.js:29:17)
Mar 17 13:58:24 raspberrypi-waveshare webide[884]:     at Cursor.execFn (/usr/share/adafruit/webide/node_modules/nedb/lib/datastore.js:520:14)
Mar 17 13:58:24 raspberrypi-waveshare webide[884]:     at callback (/usr/share/adafruit/webide/node_modules/nedb/lib/cursor.js:126:19)
Mar 17 13:58:24 raspberrypi-waveshare webide[884]:     at /usr/share/adafruit/webide/node_modules/nedb/lib/cursor.js:193:12
Mar 17 13:58:24 raspberrypi-waveshare webide[884]:     at /usr/share/adafruit/webide/node_modules/nedb/lib/datastore.js:329:14
Mar 17 13:58:24 raspberrypi-waveshare webide[884]:     at Object.async.eachSeries (/usr/share/adafruit/webide/node_modules/async/lib/async.js:130:20)
Mar 17 13:58:24 raspberrypi-waveshare webide[884]:     at /usr/share/adafruit/webide/node_modules/nedb/lib/datastore.js:323:11
Mar 17 13:58:24 raspberrypi-waveshare webide[884]:     at fn (/usr/share/adafruit/webide/node_modules/async/lib/async.js:582:34)
Mar 17 13:58:24 raspberrypi-waveshare webide[884]:     at Immediate._onImmediate (/usr/share/adafruit/webide/node_modules/async/lib/async.js:498:34)
Mar 17 13:58:24 raspberrypi-waveshare webide[884]: info: process and worker cleanup
